import { ms, sc, vs } from '../utils/responsive';

const Screen_SIZES_Scale = {
  two: sc(2),
  four: sc(4),
  six: sc(6),
  eight: sc(8),
  ten: sc(10),
  twelve: sc(12),
  fourteen: sc(14),
  sixteen: sc(16),
  eighteen: sc(18),
  twenty: sc(20),
  twentyTwo: sc(22),
  twentyFour: sc(24),
  twentySix: sc(26),
  twentyEight: sc(28),
  thirty: sc(30),
  fourty: sc(40),
  fourtyEight: sc(48),
  fifty: sc(50),
  eighty: sc(80),
  hundered: sc(100),
  oneThirty: sc(130),
  oneFifty: sc(150),
};
const Screen_SIZES_ModerateScale = {
  two: ms(2),
  four: ms(4),
  five: ms(5),
  six: ms(6),
  eight: ms(8),
  ten: ms(10),
  twelve: ms(12),
  fourteen: ms(14),
  sixteen: ms(16),
  eighteen: ms(18),
  twenty: ms(20),
  twentyTwo: ms(22),
  twentyFour: ms(24),
  twentySix: ms(26),
  twentyEight: ms(28),
  thirty: ms(30),
  fourty: ms(40),
  fourtyEight: ms(48),
  fifty: ms(50),
  eighty: ms(80),
  hundered: ms(100),
  oneThirty: ms(130),
  oneFifty: ms(150),
};
const Screen_SIZES_VerticalScale = {
  two: vs(2),
  three: vs(3),
  four: vs(4),
  six: vs(6),
  eight: vs(8),
  ten: vs(10),
  twelve: vs(12),
  fourteen: vs(14),
  sixteen: vs(16),
  eighteen: vs(18),
  twenty: vs(20),
  twentyTwo: vs(22),
  twentyFour: vs(24),
  twentySix: vs(26),
  twentyEight: vs(28),
  thirty: vs(30),
  fourty: vs(40),
  fourtyEight: vs(48),
  fifty: vs(50),

  eighty: vs(80),
  hundered: vs(100),
  oneThirty: vs(130),
  oneFifty: vs(150),
  twoFifty: vs(250),
};

export {
  Screen_SIZES_ModerateScale,
  Screen_SIZES_Scale,
  Screen_SIZES_VerticalScale,
};

export const flexOne = {
  one: 1,
};
