export const doctorsData = [
  {
    id: 1,
    name: 'Dr. Alexander Bennett, Phd',
    image: require('../assets/Images/doctor_1.png'),
    speaciality: 'Dermato-Genetics',
    rating: 5,
    specialization: 'Dermato-Endocrinology',
  },
  {
    id: 2,
    name: 'Dr. Alexander Bennett, Phd',
    image: require('../assets/Images/doctor_1.png'),
    speaciality: 'Dermato-Genetics',
    rating: 5,
    specialization: 'Dermato-Endocrinology',
  },
  {
    id: 3,
    name: 'Dr. Alexander Bennett, Phd',
    image: require('../assets/Images/doctor_1.png'),
    speaciality: 'Dermato-Genetics',
    rating: 5,
    specialization: 'Dermato-Endocrinology',
  },
  {
    id: 4,
    name: 'Dr. Alexander Bennett, Phd',
    image: require('../assets/Images/doctor_1.png'),
    speaciality: 'Dermato-Genetics',
    rating: 5,
    specialization: 'Dermato-Endocrinology',
  },
  {
    id: 5,
    name: 'Dr. Alexander Bennett, Phd',
    image: require('../assets/Images/doctor_1.png'),
    speaciality: 'Dermato-Genetics',
    rating: 5,
    specialization: 'Dermato-Endocrinology',
  },
];
